### ISSUE TITLE
PEP 609 vote?

### ISSUE THREAD

**Issue by di** [ofek/extensionlib#6]
Hi! Per [PEP 609](https://peps.python.org/pep-0609/):

> PyPA committer votes are required for, and limited to, the following kinds of proposals:
> ...
> Proposing the creation of a new tools / project in the PyPA organization.

I don't believe a vote has been initiated for the creation of this project/repo (unless I missed something) so it should probably live outside the PyPA org until that happens.

**Comment by ofek** [comment]
Ah I missed that part, sorry about that. This is the helper library mentioned in https://hackmd.io/@gaborbernat/py-packaging-summit-2022#Building-C-Extensions-without-Setuptools---Henry-Schreiner-III-and-Ofek-Lev

I'll send the vote email today, thank you! 🙏

**Comment by pfmoore** [comment]
Would it not be better to develop it in your personal account and then
transfer it when it’s ready? That’s the normal approach.

Paul

**Comment by ofek** [comment]
Yes currently figuring out how

**Comment by pfmoore** [comment]
How to do what? Transfer this project to your ownership? As a PyPA member you should be able to do that. Or if not I’ll see if I can.

**Comment by pfmoore** [comment]
It’s under settings… transfer ownership.

**Comment by ofek** [comment]
Success, thanks!

**Comment by pradyunsg** [comment]
We never moved this?

**Comment by domdfcoding** [comment]
There was a discussion here: https://mail.python.org/archives/list/pypa-committers@python.org/thread/H76Q6OO5TFHLR2IICXRRJ5ZHEPBPUVR7/

There was some reluctance, and then the discussion went off on a tangent about PyPA projects in general without ever reaching a decision, it seems.

**Comment by ofek** [comment]
@pradyunsg You voted -1 🙂

**Comment by henryiii** [comment]
Personally, I'd like to get a working implementation with scikit-build first before this gets broadcast too widely - I think it might be part of a PEP. One key feature we will need is a way to broadcast dynamic dependencies (AKA get_requires_for_build_wheel but for extensions). In our case, adding "cmake" or "ninja" can break the ability to build on anything that doesn't support rebuilt wheels (basically everywhere you need to build if you are distributing wheels!), and we can check to see if cmake/ninja are present and just continue if they are modern enough.

The work on scikit-build-core has been moving very slowly, due to me teaching this semester. I expect to start working on integration soon (1-2 tasks left before I start working on packaging).

**Comment by pradyunsg** [comment]
> There was a discussion here

Thanks for the link! ^>^

> @pradyunsg You voted -1 🙂

Indeed! And, unsurprisingly, I am in agreement with past me. :)
